# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171206_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 12, 6, 15, 33, 29, 416439, tzinfo=utc)),
        ),
    ]
