# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20171206_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 6, 15, 41, 45, 337129, tzinfo=utc)),
        ),
    ]
